export const dataAmerica: any =[
    { name: 'Argentina', dialCode: '54', code: 'AR', flag: 'https://flagcdn.com/w40/ar.png' },
    { name: 'Bolivia', dialCode: '591', code: 'BO', flag: 'https://flagcdn.com/w40/bo.png' },
    { name: 'Brasil', dialCode: '55', code: 'BR', flag: 'https://flagcdn.com/w40/br.png' },
    { name: 'Canadá', dialCode: '1', code: 'CA', flag: 'https://flagcdn.com/w40/ca.png' },
    { name: 'Chile', dialCode: '56', code: 'CL', flag: 'https://flagcdn.com/w40/cl.png' },
    { name: 'Colombia', dialCode: '57', code: 'CO', flag: 'https://flagcdn.com/w40/co.png' },
    { name: 'Costa Rica', dialCode: '506', code: 'CR', flag: 'https://flagcdn.com/w40/cr.png' },
    { name: 'Cuba', dialCode: '53', code: 'CU', flag: 'https://flagcdn.com/w40/cu.png' },
    { name: 'Ecuador', dialCode: '593', code: 'EC', flag: 'https://flagcdn.com/w40/ec.png' },
    { name: 'El Salvador', dialCode: '503', code: 'SV', flag: 'https://flagcdn.com/w40/sv.png' },
    { name: 'Estados Unidos', dialCode: '1', code: 'US', flag: 'https://flagcdn.com/w40/us.png' },
    { name: 'Guatemala', dialCode: '502', code: 'GT', flag: 'https://flagcdn.com/w40/gt.png' },
    { name: 'Honduras', dialCode: '504', code: 'HN', flag: 'https://flagcdn.com/w40/hn.png' },
    { name: 'México', dialCode: '52', code: 'MX', flag: 'https://flagcdn.com/w40/mx.png' },
    { name: 'Nicaragua', dialCode: '505', code: 'NI', flag: 'https://flagcdn.com/w40/ni.png' },
    { name: 'Panamá', dialCode: '507', code: 'PA', flag: 'https://flagcdn.com/w40/pa.png' },
    { name: 'Paraguay', dialCode: '595', code: 'PY', flag: 'https://flagcdn.com/w40/py.png' },
    { name: 'Perú', dialCode: '51', code: 'PE', flag: 'https://flagcdn.com/w40/pe.png' },
    { name: 'Rep. Dominicana', dialCode: '1', code: 'DO', flag: 'https://flagcdn.com/w40/do.png' },
    { name: 'Uruguay', dialCode: '598', code: 'UY', flag: 'https://flagcdn.com/w40/uy.png' },
    { name: 'Venezuela', dialCode: '58', code: 'VE', flag: 'https://flagcdn.com/w40/ve.png' },
];