import {
  MatButtonModule,
  MatAutocompleteModule,
  MatButtonToggleModule,
  MatChipsModule,
  MatDialogModule,
  MatRadioModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatSortModule,
  MatStepperModule,
  MatCheckboxModule,
  MatSidenavModule,
  MatIconModule,
  MatToolbarModule,
  MatListModule,
  MatProgressBarModule,
  MatCardModule,
  MatTooltipModule,
  MatDividerModule,
  MatInputModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatTableModule,
  MatProgressSpinnerModule,
  MatGridListModule,
  MatTabsModule,
  MatSelectModule,
  MatSnackBarModule,
  MatRippleModule,
  MatDatepickerModule,
  MatPaginatorModule,
  MatMenuModule,
  MatBadgeModule,
  MatNativeDateModule // <-- AÑADIR AQUÍ
} from '@angular/material';
import { ScrollDispatchModule } from '@angular/cdk/scrolling';
import { NgModule } from '@angular/core';

@NgModule({
  imports: [
    MatButtonModule,
    MatAutocompleteModule,
    MatButtonToggleModule,
    MatChipsModule,
    MatDialogModule,
    MatNativeDateModule, // <-- Y AQUÍ
    MatRadioModule,
    MatBadgeModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSortModule,
    MatStepperModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatMenuModule,
    MatIconModule,
    MatToolbarModule,
    MatListModule,
    MatProgressBarModule,
    MatCardModule,
    MatTooltipModule,
    MatDividerModule,
    MatInputModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatTableModule,
    MatProgressSpinnerModule,
    MatGridListModule,
    MatSnackBarModule,
    MatDatepickerModule,
    MatRippleModule,
    MatPaginatorModule,
    MatTabsModule,
    MatSelectModule,
    ScrollDispatchModule
  ],
  exports: [
    MatButtonModule,
    MatAutocompleteModule,
    MatButtonToggleModule,
    MatChipsModule,
    MatDialogModule,
    MatNativeDateModule, // <-- Y AQUÍ TAMBIÉN
    MatRadioModule,
    MatBadgeModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSortModule,
    MatStepperModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatMenuModule,
    MatIconModule,
    MatToolbarModule,
    MatListModule,
    MatProgressBarModule,
    MatCardModule,
    MatTooltipModule,
    MatDividerModule,
    MatInputModule,
    MatExpansionModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatTableModule,
    MatProgressSpinnerModule,
    MatGridListModule,
    MatSnackBarModule,
    MatRippleModule,
    MatPaginatorModule,
    MatTabsModule,
    MatSelectModule,
    ScrollDispatchModule
  ],
})
export class MyOwnCustomMaterialModule { }
